export const dicionario = [
    { palavra: 'abacate', definicoes: ['Fruto do abacateiro.', 'Verde por fora, gostoso por dentro.'] },
    { palavra: 'abraço', definicoes: ['Ato de envolver com os braços.', 'Demonstração de afeto.'] },
    { palavra: 'alegria', definicoes: ['Sentimento de felicidade.', 'Estado de espírito positivo.'] },
    { palavra: 'amizade', definicoes: ['Relação de afeto entre pessoas.', 'Companheirismo duradouro.'] },
    { palavra: 'amor', definicoes: ['Sentimento profundo de carinho.', 'Afeição intensa por alguém.'] },
    { palavra: 'banana', definicoes: ['Fruta amarela e rica em potássio.', 'Muito consumida no Brasil.'] },
    { palavra: 'brinquedo', definicoes: ['Objeto usado para brincar.', 'Diversão infantil.'] },
    { palavra: 'cachorro', definicoes: ['Animal doméstico fiel.', 'Melhor amigo do homem.'] },
    { palavra: 'caderno', definicoes: ['Material escolar para anotações.', 'Contém folhas de papel.'] },
    { palavra: 'café', definicoes: ['Bebida estimulante feita de grãos.', 'Tradicional no café da manhã.'] },
    { palavra: 'carinho', definicoes: ['Ato de demonstrar afeto.', 'Gentileza e ternura.'] },
    { palavra: 'carro', definicoes: ['Veículo motorizado com rodas.', 'Usado para transporte.'] },
    { palavra: 'casa', definicoes: ['Lugar para morar.', 'Abrigo e conforto.'] },
    { palavra: 'chuva', definicoes: ['Precipitação de água.', 'Molha tudo.'] },
    { palavra: 'coração', definicoes: ['Órgão que bombeia sangue.', 'Símbolo do amor.'] },
    { palavra: 'dente', definicoes: ['Parte dura na boca.', 'Serve para mastigar.'] },
    { palavra: 'desenho', definicoes: ['Representação gráfica.', 'Atividade criativa.'] },
    { palavra: 'dedo', definicoes: ['Extremidade da mão.', 'Serve para tocar ou pegar.'] },
    { palavra: 'escola', definicoes: ['Instituição de ensino.', 'Lugar de aprender.'] },
    { palavra: 'estrela', definicoes: ['Corpo celeste luminoso.', 'Brilha no céu à noite.'] },
    { palavra: 'família', definicoes: ['Grupo de pessoas com laços.', 'Base social e afetiva.'] },
    { palavra: 'felicidade', definicoes: ['Estado de bem-estar.', 'Alegria plena.'] },
    { palavra: 'festa', definicoes: ['Celebração com pessoas.', 'Motivo de alegria.'] },
    { palavra: 'flores', definicoes: ['Parte bonita da planta.', 'Símbolo de beleza.'] },
    { palavra: 'frio', definicoes: ['Baixa temperatura.', 'Clima gelado.'] },
    { palavra: 'gato', definicoes: ['Animal doméstico felino.', 'Ágil e independente.'] },
    { palavra: 'giz', definicoes: ['Material para escrever no quadro.', 'Branco e quebradiço.'] },
    { palavra: 'guitarra', definicoes: ['Instrumento musical com cordas.', 'Usada no rock.'] },
    { palavra: 'herói', definicoes: ['Pessoa admirada por feitos.', 'Figura de coragem.'] },
    { palavra: 'história', definicoes: ['Relato de eventos.', 'Disciplina escolar.'] },
    { palavra: 'homem', definicoes: ['Ser humano do sexo masculino.', 'Pessoa adulta.'] },
    { palavra: 'ideia', definicoes: ['Conceito ou pensamento.', 'Origem de ações.'] },
    { palavra: 'infância', definicoes: ['Período inicial da vida.', 'Tempo de brincar.'] },
    { palavra: 'irmão', definicoes: ['Filho dos mesmos pais.', 'Companheiro de vida.'] },
    { palavra: 'janela', definicoes: ['Abertura em paredes.', 'Serve para ventilação.'] },
    { palavra: 'jardim', definicoes: ['Área com plantas e flores.', 'Beleza natural.'] },
    { palavra: 'joia', definicoes: ['Objeto de adorno precioso.', 'Valor sentimental ou monetário.'] },
    { palavra: 'júri', definicoes: ['Grupo que julga em tribunal.', 'Decide sentenças.'] },
    { palavra: 'leite', definicoes: ['Líquido branco nutritivo.', 'Produzido por mamíferos.'] },
    { palavra: 'livro', definicoes: ['Conjunto de páginas escritas.', 'Instrumento de leitura.'] },
    { palavra: 'luz', definicoes: ['Forma de energia visível.', 'Ilumina ambientes.'] },
    { palavra: 'mamãe', definicoes: ['Forma carinhosa de mãe.', 'Pessoa que cuida.'] },
    { palavra: 'mar', definicoes: ['Grande massa de água salgada.', 'Oceano.'] },
    { palavra: 'mesa', definicoes: ['Móvel com superfície plana.', 'Serve para refeições.'] },
    { palavra: 'menino', definicoes: ['Criança do sexo masculino.', 'Jovem.'] },
    { palavra: 'mulher', definicoes: ['Pessoa do sexo feminino.', 'Adulta.'] },
    { palavra: 'música', definicoes: ['Arte dos sons.', 'Pode ser cantada ou instrumental.'] },
    { palavra: 'noite', definicoes: ['Período sem luz solar.', 'Hora de dormir.'] },
    { palavra: 'nuvem', definicoes: ['Aglomerado de gotículas no céu.', 'Precede a chuva.'] },
    { palavra: 'olhos', definicoes: ['Órgãos da visão.', 'Captam luz e imagem.'] },
    { palavra: 'ovo', definicoes: ['Produzido por aves.', 'Alimento com casca.'] },
    { palavra: 'pai', definicoes: ['Homem que tem filhos.', 'Responsável familiar.'] },
    { palavra: 'pão', definicoes: ['Alimento feito com farinha.', 'Presente no café da manhã.'] },
    { palavra: 'papel', definicoes: ['Material para escrever.', 'Feito de celulose.'] },
    { palavra: 'passarinho', definicoes: ['Ave pequena.', 'Canta e voa.'] },
    { palavra: 'peixe', definicoes: ['Animal aquático.', 'Nada com nadadeiras.'] },
    { palavra: 'perna', definicoes: ['Parte do corpo usada para andar.', 'Inferior ao tronco.'] },
    { palavra: 'porta', definicoes: ['Abertura para entrada.', 'Pode ser aberta ou fechada.'] },
    { palavra: 'quadro', definicoes: ['Estrutura para pendurar ou escrever.', 'Pode ter imagem ou texto.'] },
    { palavra: 'quente', definicoes: ['Alta temperatura.', 'Oposto de frio.'] },
    { palavra: 'riso', definicoes: ['Ato de rir.', 'Expressão de alegria.'] },
    { palavra: 'rio', definicoes: ['Curso de água doce.', 'Corre em direção ao mar.'] },
    { palavra: 'rosa', definicoes: ['Flor com espinhos.', 'Símbolo de amor.'] },
    { palavra: 'sabão', definicoes: ['Usado para limpeza.', 'Faz espuma.'] },
    { palavra: 'sabor', definicoes: ['Sensação gustativa.', 'Pode ser doce, salgado, etc.'] },
    { palavra: 'saúde', definicoes: ['Estado de bem-estar físico e mental.', 'Importante para viver bem.'] },
    { palavra: 'sino', definicoes: ['Instrumento que toca ao ser batido.', 'Usado em igrejas.'] },
    { palavra: 'sol', definicoes: ['Estrela do sistema solar.', 'Fonte de luz e calor.'] },
    { palavra: 'sombra', definicoes: ['Área escura sem luz direta.', 'Formada pela obstrução da luz.'] },
    { palavra: 'som', definicoes: ['Vibração percebida pelos ouvidos.', 'Pode ser música ou ruído.'] },
    { palavra: 'sonho', definicoes: ['Sequência de imagens ao dormir.', 'Desejo futuro.'] },
    { palavra: 'tarde', definicoes: ['Período após o meio-dia.', 'Antes da noite.'] },
    { palavra: 'telefone', definicoes: ['Aparelho de comunicação.', 'Usado para chamadas.'] },
    { palavra: 'terra', definicoes: ['Planeta onde vivemos.', 'Solo.'] },
    { palavra: 'tia', definicoes: ['Irmã do pai ou mãe.', 'Parente.'] },
    { palavra: 'tempo', definicoes: ['Dimensão que mede a duração.', 'Clima ou cronologia.'] },
    { palavra: 'urso', definicoes: ['Animal grande e peludo.', 'Mamífero selvagem.'] },
    { palavra: 'uva', definicoes: ['Fruta pequena e redonda.', 'Pode virar vinho.'] },
    { palavra: 'vaca', definicoes: ['Animal de fazenda.', 'Produz leite.'] },
    { palavra: 'vassoura', definicoes: ['Usada para limpar o chão.', 'Feita de cerdas.'] },
    { palavra: 'vento', definicoes: ['Ar em movimento.', 'Sopra com força.'] },
    { palavra: 'vidro', definicoes: ['Material transparente.', 'Quebra fácil.'] },
    { palavra: 'violão', definicoes: ['Instrumento de cordas.', 'Muito usado na MPB.'] },
    { palavra: 'vôo', definicoes: ['Ato de voar.', 'Feito por aves ou aviões.'] },
    { palavra: 'xampu', definicoes: ['Produto para lavar cabelos.', 'Espuma perfumada.'] },
    { palavra: 'xadrez', definicoes: ['Jogo de tabuleiro estratégico.', 'Rei, rainha, peão.'] },
    { palavra: 'xícara', definicoes: ['Recipiente para bebidas quentes.', 'Usado com café ou chá.'] },
    { palavra: 'zebra', definicoes: ['Animal listrado.', 'Parece um cavalo branco com listras.'] },
    { palavra: 'zoológico', definicoes: ['Lugar com animais.', 'Aberto ao público para visitação.'] },
    { palavra: 'abacaxi', definicoes: ['Fruta tropical com casca espinhosa.', 'Sabor doce e ácido.'] },
    { palavra: 'anel', definicoes: ['Joia usada nos dedos.', 'Símbolo de compromisso.'] },
    { palavra: 'barco', definicoes: ['Veículo que navega na água.', 'Pode ser a remo ou a motor.'] },
    { palavra: 'colher', definicoes: ['Utensílio de cozinha.', 'Usada para comer alimentos líquidos.'] },
    { palavra: 'dedal', definicoes: ['Objeto que protege o dedo ao costurar.', 'Pequeno e metálico.'] },
    { palavra: 'espelho', definicoes: ['Superfície que reflete imagens.', 'Usado para ver o próprio rosto.'] },
    { palavra: 'flauta', definicoes: ['Instrumento musical de sopro.', 'Produz sons suaves.'] },
    { palavra: 'índio', definicoes: ['Habitante nativo das Américas.', 'Cultura rica e diversa.'] },
    { palavra: 'navio', definicoes: ['Embarcação de grande porte.', 'Transporte marítimo.'] },
    { palavra: 'pinguim', definicoes: ['Ave que vive em regiões frias.', 'Não voa, mas nada muito bem.'] },
    { palavra: 'tapete', definicoes: ['Peça usada no chão.', 'Decora e protege o piso.'] },
  ];
  
  